# Generated by Django 2.1.2 on 2019-01-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190130_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='submission',
            name='answer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
