# Generated by Django 2.1.2 on 2019-01-13 14:08

from django.db import migrations, models
import puzzle.models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.FileField(blank=True, upload_to=puzzle.models.meme_directory_path),
        ),
        migrations.AlterField(
            model_name='meme',
            name='sound',
            field=models.FileField(blank=True, upload_to=puzzle.models.meme_directory_path),
        ),
    ]
