# Generated by Django 2.1.2 on 2019-01-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190127_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
