# Generated by Django 2.1.2 on 2019-01-04 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(unique=True)),
                ('pdf', models.FileField(null=True, upload_to='puzzle')),
                ('answer', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('startgame_key', models.CharField(blank=True, max_length=6, null=True)),
                ('endgame_key', models.CharField(blank=True, max_length=6, null=True)),
                ('penalty_key', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startgame_time', models.DateTimeField(null=True)),
                ('endgame_time', models.DateTimeField(null=True)),
                ('puzzle_get_time', models.DateTimeField(null=True)),
                ('puzzle_sub_time', models.DateTimeField(null=True)),
                ('puzzle_tried', models.IntegerField(default=0)),
                ('puzzle_finished', models.BooleanField(default=False)),
                ('game_finished', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunt.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='n', max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunt.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
