# Generated by Django 2.1.2 on 2019-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='location_clue',
            field=models.FileField(null=True, upload_to='location'),
        ),
    ]
