# Generated by Django 2.1.2 on 2019-01-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_game_location_clue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='startgame_key',
        ),
        migrations.RemoveField(
            model_name='teamgame',
            name='startgame_time',
        ),
    ]
